### ISSUE TITLE
不能全部显示

### ISSUE THREAD

**Issue by chiheye** [giserHacter/osgb-slpk#4]
osgb优化输出slpk后，加载到pro中不能全域显示，可否全域显示

https://user-images.githubusercontent.com/42902754/118491157-4737b800-b751-11eb-8b0a-ae1e142183cd.mp4

**Comment by giserHacter** [comment]
目前是pro的bug，已经在修改了，但是在网页端上面显示是没有问题的，如果你非要在pro里面显示的话，你可以使用节点合并工具来跑一下

chiheye ***@***.***> 于2021年5月17日周一 下午8:47写道：

**Comment by chiheye** [comment]
> 目前是pro的bug，已经在修改了，但是在网页端上面显示是没有问题的，如果你非要在pro里面显示的话，你可以使用节点合并工具来跑一下 chiheye ***@***.***> 于2021年5月17日周一 下午8:47写道：
> […](#)

好的
